### ISSUE TITLE
Limitations of reference genome to human

### ISSUE THREAD

**Issue by cheesemania** [xikanfeng2/SCYN#1]
Thank you for the software! A quick question - is the analysis limited to human genome references, we would like to apply this approach to non-human samples

**Comment by xikanfeng2** [comment]
> Thank you for the software! A quick question - is the analysis limited to human genome references, we would like to apply this approach to non-human samples

Thanks for using our software. Currently, we only support the human genome. May I know which species you want to apply to? We can update our source code to support the mouse genome if you need it.
